# Generated by Django 5.2.11 on 2026-02-14 20:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.CharField(max_length=18, unique=True, validators=[apps.core.validators.validate_document], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
