# Generated by Django 5.2.11 on 2026-02-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatushistory",
            name="changed_by",
            field=models.CharField(default="System", max_length=255),
            preserve_default=False,
        ),
    ]
