# Generated by Django 5.2.11 on 2026-02-14 22:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código interno')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='Quantidade em estoque')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'products',
                'indexes': [models.Index(fields=['stock_quantity'], name='products_stock_q_5d82ff_idx'), models.Index(fields=['deleted_at'], name='products_deleted_c3f9ae_idx')],
            },
        ),
    ]
